
# SEO
title: 3v1lW1th1n
description: A bold typographic theme inspired by Swiss design.

# social
social_link: twitter
social_username: 3v1lW1th1n
github_repo: athena # the GitHub repo name for your project
github_username: 3v1lW1th1n
theme_color: blue

# Theme
remote_theme: '3v1lw1th1n.github.io'
baseurl: '/athena'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


